[package]
name = "mirai-bot-rs"
version = "0.1.0"
authors = ["Brussell"]
edition = "2018"

[dependencies]
dotenv = "0.13.0"
reqwest = "0.9.11"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.serenity]
default-features = true
version = "0.5"
